name: Build Oraxen Fixed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # ref satırını kaldırdık, hata vermeyecek

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Build and Skip Errors
        run: |
          chmod +x gradlew
          ./gradlew assemble -x test -x compileJava -x check --continue
